# Generated by Django 5.1.4 on 2024-12-20 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='cafecalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menu_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='seat',
            fields=[
                ('seat_number', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('reservation_number', models.TextField(blank=True, max_length=20, null=True)),
                ('taketime', models.DateTimeField(blank=True, null=True)),
                ('staytime', models.DurationField(blank=True, null=True)),
                ('preorder', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('customer_number', models.CharField(default='', editable=False, max_length=20, unique=True, verbose_name='顧客番号')),
                ('username', models.CharField(default='', max_length=20, verbose_name='アカウント名')),
                ('family_name', models.CharField(default='', max_length=20, verbose_name='苗字')),
                ('personal_name', models.CharField(default='', max_length=20, verbose_name='名前')),
                ('password', models.CharField(default='', max_length=20, verbose_name='パスワード')),
                ('telephone_number', models.CharField(default='', max_length=20, verbose_name='電話番号')),
                ('mail_address', models.CharField(default='', max_length=100, unique=True, verbose_name='メールアドレス')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='crud_user_groups', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='crud_user_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_number', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('order_zahl', models.PositiveSmallIntegerField()),
                ('order_customer_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deicafeapp.customer')),
                ('order_menu_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deicafeapp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('reservation_number', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('reservation_taketime', models.DateTimeField()),
                ('reservation_staytime', models.DurationField()),
                ('preorder', models.BooleanField()),
                ('details', models.TextField()),
                ('reservation_customer_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deicafeapp.customer')),
                ('reservation_seat_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deicafeapp.seat')),
            ],
        ),
    ]
