# Generated by Django 5.1.4 on 2024-12-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deicafeapp', '0002_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mail_address',
            field=models.CharField(default='', max_length=100, verbose_name='メールアドレス'),
        ),
    ]
