# Generated by Django 5.1.4 on 2024-12-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deicafeapp', '0003_alter_customer_mail_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
